### ISSUE TITLE
4.9.2 of build-info-extractor-gradle seems to be attempting to pull an unreachable snapshot

### ISSUE THREAD

**Issue by tellisnz** [jfrog/build-info#215] opened 2019-02-20 10:49 UTC
when attempting to use 4.9.2 of the build-info-extractor-gradle plugin using:

```
    repositories {
        mavenCentral()
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
...
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.9.2"
```
resolving the classpath fails with:
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jfrog.buildinfo:build-info-extractor:2.13.x-SNAPSHOT.
     Required by:
         project : > org.jfrog.buildinfo:build-info-extractor-gradle:4.9.2
      > Could not resolve org.jfrog.buildinfo:build-info-extractor:2.13.x-SNAPSHOT.
         > Could not get resource 'https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-extractor/2.13.x-SNAPSHOT/build-info-extractor-2.13.x-SNAPSHOT.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-extractor/2.13.x-SNAPSHOT/build-info-extractor-2.13.x-SNAPSHOT.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve org.jfrog.buildinfo:build-info-extractor:2.13.x-SNAPSHOT.
         > Could not get resource 'https://plugins.gradle.org/m2/org/jfrog/buildinfo/build-info-extractor/2.13.x-SNAPSHOT/build-info-extractor-2.13.x-SNAPSHOT.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/org/jfrog/buildinfo/build-info-extractor/2.13.x-SNAPSHOT/build-info-extractor-2.13.x-SNAPSHOT.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

using 4.9.1 works ok

**Comment by yahavi** [comment] 2019-02-20 10:52
Thanks, @tellisnz, for reporting this issue. 
We are now releasing 4.9.3. This version will include a fix for this issue.
In the meantime, you can use 4.9.1.

**Comment by yahavi** [comment] 2019-02-20 11:40
@tellisnz,
build-info-extractor-gradle 4.9.3 is released.
We apologize for the inconvenience caused by this issue.

**Closed** 2019-02-20 12:55 UTC
